# Generated by Django 4.2.7 on 2024-01-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApi', '0002_remove_content_course_course_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='courseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='courseApi.course'),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
